name: 'Jest Coverage Badges AWS'
description: 'Create Jest coverage badges and upload them to a AWS S3 bucket'
inputs:
  coverage-path:
    description: 'Path where your coverage-summary is located'
  aws-bucket:  # id of input
    description: 'Name of the bucket where the badges will be located'
    required: true
  aws-bucket-folder:
    description: 'Name of the folder/key in the bucket where the badges will be located'
    required: true
  
outputs:
  badges-urls: # output will be available to future steps
    description: 'Path where your badges where upload on the bucket'
runs:
  using: 'node16'
  main: 'dist/index.js'

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'info'
  color: 'gray-dark'

